-- ============================================================
--  UITogether - CONSOLIDATED DATABASE SCHEMA
-- ------------------------------------------------------------
--  GENERATED FILE - do not edit by hand.
--  Regenerate with:  npm run db:schema
--  Source of truth:  database/migrations/*.sql
--
--  Generated: 2026-09-08T18:24:59.752Z
--  Built from 9 migration file(s).
--
--  Normal setup does NOT need this file - just run:
--      npm run db:setup
--
--  To load it manually instead, against an EXISTING database:
--      psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -f database/schema.sql
--
--  PostgreSQL has no "USE" statement and cannot CREATE DATABASE from inside
--  a script that also builds tables, so the target database is chosen by the
--  connection you run this with. Create it first if it does not exist:
--      createdb uitogether_db
-- ============================================================


-- ############################################################
-- # 001_create_users.sql
-- ############################################################

-- ============================================================
-- Migration 001 : users
-- Core account table. Roles are NEVER chosen by the client:
-- the API always inserts 'student'; admins are promoted manually.
-- Only @gmail.com addresses are accepted (relaxed in migration 009).
--
-- PORTED FROM MySQL: this project originally ran on MySQL. The
-- differences that matter across every migration file:
--   AUTO_INCREMENT      -> GENERATED BY DEFAULT AS IDENTITY
--                          ("BY DEFAULT", not "ALWAYS", so seed.sql can
--                           still insert explicit ids)
--   ENUM('a','b')       -> VARCHAR + CHECK constraint. A native PostgreSQL
--                          enum would also work, but a CHECK keeps every
--                          column plain text, so the driver never has to
--                          cast a bound parameter into a custom type.
--   KEY idx_... (...)   -> a separate CREATE INDEX statement
--   COMMENT '...'       -> COMMENT ON COLUMN
--   ON UPDATE CURRENT_TIMESTAMP -> set_updated_at(), the trigger below
--   REGEXP              -> the ~ operator
-- ============================================================

-- ------------------------------------------------------------
-- Shared trigger function: MySQL keeps updated_at current by itself with
-- "ON UPDATE CURRENT_TIMESTAMP". PostgreSQL has no such column clause, so
-- every table below attaches this BEFORE UPDATE trigger instead.
-- ------------------------------------------------------------
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at := CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TABLE IF NOT EXISTS users (
  user_id       INTEGER      GENERATED BY DEFAULT AS IDENTITY,
  name          VARCHAR(100) NOT NULL,
  email         VARCHAR(191) NOT NULL,
  tnt           VARCHAR(30)  NOT NULL,
  academic_year VARCHAR(30)  NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  role          VARCHAR(16)  NOT NULL DEFAULT 'student',
  created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_users PRIMARY KEY (user_id),
  CONSTRAINT uq_users_email UNIQUE (email),
  CONSTRAINT uq_users_tnt   UNIQUE (tnt),
  CONSTRAINT chk_users_role
    CHECK (role IN ('student', 'admin')),
  CONSTRAINT chk_users_email_gmail
    CHECK (email ~ '^[a-z0-9._%+-]+@gmail\.com$'),
  CONSTRAINT chk_users_name_not_blank
    CHECK (char_length(trim(name)) >= 2)
);

COMMENT ON COLUMN users.tnt           IS 'University roll / TNT number, unique per student';
COMMENT ON COLUMN users.academic_year IS 'e.g. "1st Year", "2nd Year", "Final Year"';
COMMENT ON COLUMN users.password_hash IS 'bcrypt hash - plaintext is never stored';

CREATE INDEX IF NOT EXISTS idx_users_role ON users (role);

DROP TRIGGER IF EXISTS trg_users_updated_at ON users;
CREATE TRIGGER trg_users_updated_at
BEFORE UPDATE ON users
FOR EACH ROW EXECUTE FUNCTION set_updated_at();


-- ############################################################
-- # 002_create_study_buddy_profiles.sql
-- ############################################################

-- ============================================================
-- Migration 002 : study_buddy_profiles
-- Exactly ONE profile per user (enforced by uq_profiles_user_id).
-- telegram / viber are PRIVATE columns: the repository layer has
-- a "public" projection that never selects them, and they are only
-- read through the match-aware query path.
-- ============================================================

CREATE TABLE IF NOT EXISTS study_buddy_profiles (
  profile_id      INTEGER       GENERATED BY DEFAULT AS IDENTITY,
  user_id         INTEGER       NOT NULL,
  nickname        VARCHAR(60)   NOT NULL,
  semester        VARCHAR(30)   NOT NULL,
  study_style     VARCHAR(20)   NOT NULL DEFAULT 'mixed',
  weak_subjects   VARCHAR(500)  NULL,
  strong_subjects VARCHAR(500)  NULL,
  wanna_meet      VARCHAR(12)   NOT NULL DEFAULT 'both',
  notes           VARCHAR(1000) NULL,
  telegram        VARCHAR(100)  NULL,
  viber           VARCHAR(100)  NULL,
  created_at      TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at      TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_profiles PRIMARY KEY (profile_id),
  CONSTRAINT uq_profiles_user_id UNIQUE (user_id),
  CONSTRAINT fk_profiles_user
    FOREIGN KEY (user_id) REFERENCES users (user_id)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT chk_profiles_study_style
    CHECK (study_style IN ('solo_focus', 'group_discussion', 'quiet_library', 'online_call', 'mixed')),
  CONSTRAINT chk_profiles_wanna_meet
    CHECK (wanna_meet IN ('online', 'in_person', 'both')),
  CONSTRAINT chk_profiles_has_contact
    CHECK (telegram IS NOT NULL OR viber IS NOT NULL)
);

COMMENT ON COLUMN study_buddy_profiles.semester        IS 'e.g. "Semester 1" ... "Semester 8"';
COMMENT ON COLUMN study_buddy_profiles.weak_subjects   IS 'Comma separated subject list';
COMMENT ON COLUMN study_buddy_profiles.strong_subjects IS 'Comma separated subject list';
COMMENT ON COLUMN study_buddy_profiles.telegram        IS 'PRIVATE - @username or t.me link, revealed only on mutual match';
COMMENT ON COLUMN study_buddy_profiles.viber           IS 'PRIVATE - phone or viber link, revealed only on mutual match';

CREATE INDEX IF NOT EXISTS idx_profiles_semester    ON study_buddy_profiles (semester);
CREATE INDEX IF NOT EXISTS idx_profiles_study_style ON study_buddy_profiles (study_style);
CREATE INDEX IF NOT EXISTS idx_profiles_wanna_meet  ON study_buddy_profiles (wanna_meet);

DROP TRIGGER IF EXISTS trg_profiles_updated_at ON study_buddy_profiles;
CREATE TRIGGER trg_profiles_updated_at
BEFORE UPDATE ON study_buddy_profiles
FOR EACH ROW EXECUTE FUNCTION set_updated_at();


-- ############################################################
-- # 003_create_buddy_requests.sql
-- ############################################################

-- ============================================================
-- Migration 003 : buddy_requests
-- One row per (sender -> receiver) direction.
--   * trg_requests_not_self_* : a user can never request themselves
--   * uq_requests_pair        : no duplicate request in the same direction
--                               (a rejected row is revived to 'pending'
--                                by the service instead of inserting a dup)
-- A MUTUAL MATCH is simply status = 'accepted'.
--
-- WHY A TRIGGER AND NOT A CHECK CONSTRAINT
-- PostgreSQL would happily accept CHECK (sender_id <> receiver_id) here -
-- the restriction that forced a trigger was MySQL's, which prohibits foreign
-- key referential actions on any column named in a CHECK. The trigger is kept
-- so the rejection message stays identical to the one the API already
-- surfaces, and so this file still mirrors the schema it was ported from.
-- ============================================================

CREATE TABLE IF NOT EXISTS buddy_requests (
  request_id  INTEGER     GENERATED BY DEFAULT AS IDENTITY,
  sender_id   INTEGER     NOT NULL,
  receiver_id INTEGER     NOT NULL,
  status      VARCHAR(12) NOT NULL DEFAULT 'pending',
  created_at  TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at  TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_requests PRIMARY KEY (request_id),
  CONSTRAINT uq_requests_pair UNIQUE (sender_id, receiver_id),
  CONSTRAINT fk_requests_sender
    FOREIGN KEY (sender_id) REFERENCES users (user_id)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_requests_receiver
    FOREIGN KEY (receiver_id) REFERENCES users (user_id)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT chk_requests_status
    CHECK (status IN ('pending', 'accepted', 'rejected'))
);

CREATE INDEX IF NOT EXISTS idx_requests_receiver_status ON buddy_requests (receiver_id, status);
CREATE INDEX IF NOT EXISTS idx_requests_sender_status   ON buddy_requests (sender_id, status);

-- MySQL raised this with SIGNAL SQLSTATE '45000'; the PostgreSQL equivalent
-- is RAISE EXCEPTION, which reports SQLSTATE P0001. error.middleware.js maps
-- P0001 to a 422 and shows the message text, exactly as it did for 45000.
CREATE OR REPLACE FUNCTION trg_requests_not_self()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.sender_id = NEW.receiver_id THEN
    RAISE EXCEPTION 'You cannot send a buddy request to yourself';
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_requests_not_self_bi ON buddy_requests;
CREATE TRIGGER trg_requests_not_self_bi
BEFORE INSERT ON buddy_requests
FOR EACH ROW EXECUTE FUNCTION trg_requests_not_self();

DROP TRIGGER IF EXISTS trg_requests_not_self_bu ON buddy_requests;
CREATE TRIGGER trg_requests_not_self_bu
BEFORE UPDATE ON buddy_requests
FOR EACH ROW EXECUTE FUNCTION trg_requests_not_self();

DROP TRIGGER IF EXISTS trg_requests_updated_at ON buddy_requests;
CREATE TRIGGER trg_requests_updated_at
BEFORE UPDATE ON buddy_requests
FOR EACH ROW EXECUTE FUNCTION set_updated_at();


-- ############################################################
-- # 004_create_competitions.sql
-- ############################################################

-- ============================================================
-- Migration 004 : competitions
-- ADMIN-ONLY write table. Enforcement is layered:
--   1. route  -> authenticate + requireAdmin middleware
--   2. DB     -> trigger in migration 008 rejects a created_by
--                that is not an admin user (defence in depth)
-- Students can only read.
-- ============================================================

CREATE TABLE IF NOT EXISTS competitions (
  competition_id INTEGER      GENERATED BY DEFAULT AS IDENTITY,
  title          VARCHAR(150) NOT NULL,
  description    TEXT         NULL,
  event_date     DATE         NOT NULL,
  event_time     TIME         NULL,
  location       VARCHAR(150) NULL,
  organizer      VARCHAR(120) NULL,
  image_url      VARCHAR(500) NULL,
  created_by     INTEGER      NULL,
  created_at     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_competitions PRIMARY KEY (competition_id),
  CONSTRAINT fk_competitions_created_by
    FOREIGN KEY (created_by) REFERENCES users (user_id)
    ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT chk_competitions_title_not_blank
    CHECK (char_length(trim(title)) >= 3)
);

COMMENT ON COLUMN competitions.created_by IS 'FK -> users.user_id, must be an admin (see trigger)';

CREATE INDEX IF NOT EXISTS idx_competitions_event_date ON competitions (event_date);
CREATE INDEX IF NOT EXISTS idx_competitions_created_by ON competitions (created_by);

DROP TRIGGER IF EXISTS trg_competitions_updated_at ON competitions;
CREATE TRIGGER trg_competitions_updated_at
BEFORE UPDATE ON competitions
FOR EACH ROW EXECUTE FUNCTION set_updated_at();


-- ############################################################
-- # 005_create_lost_found.sql
-- ############################################################

-- ============================================================
-- Migration 005 : lost_found
-- Any student may post. Ownership rule (owner OR admin) is
-- enforced in lostFound.service.js on update/delete.
-- ============================================================

CREATE TABLE IF NOT EXISTS lost_found (
  item_id      INTEGER      GENERATED BY DEFAULT AS IDENTITY,
  user_id      INTEGER      NOT NULL,
  type         VARCHAR(8)   NOT NULL,
  title        VARCHAR(150) NOT NULL,
  description  TEXT         NULL,
  location     VARCHAR(150) NULL,
  item_date    DATE         NULL,
  image_url    VARCHAR(500) NULL,
  contact_info VARCHAR(150) NULL,
  status       VARCHAR(10)  NOT NULL DEFAULT 'active',
  created_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_lost_found PRIMARY KEY (item_id),
  CONSTRAINT fk_lost_found_user
    FOREIGN KEY (user_id) REFERENCES users (user_id)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT chk_lost_found_type
    CHECK (type IN ('lost', 'found')),
  CONSTRAINT chk_lost_found_status
    CHECK (status IN ('active', 'resolved')),
  CONSTRAINT chk_lost_found_title_not_blank
    CHECK (char_length(trim(title)) >= 3)
);

COMMENT ON COLUMN lost_found.item_date    IS 'Date the item was lost / found';
COMMENT ON COLUMN lost_found.contact_info IS 'Public on purpose - poster chooses what to show';

CREATE INDEX IF NOT EXISTS idx_lost_found_user        ON lost_found (user_id);
CREATE INDEX IF NOT EXISTS idx_lost_found_type_status ON lost_found (type, status);
CREATE INDEX IF NOT EXISTS idx_lost_found_created_at  ON lost_found (created_at);

DROP TRIGGER IF EXISTS trg_lost_found_updated_at ON lost_found;
CREATE TRIGGER trg_lost_found_updated_at
BEFORE UPDATE ON lost_found
FOR EACH ROW EXECUTE FUNCTION set_updated_at();


-- ############################################################
-- # 006_create_polls.sql
-- ############################################################

-- ============================================================
-- Migration 006 : polls, poll_options, votes
--
-- "One vote per user per poll" is enforced BY THE DATABASE with
--   UNIQUE (poll_id, user_id)  -> uq_votes_one_per_poll
--
-- A vote can also never point at an option from a different poll:
-- votes carries (poll_id, option_id) and a COMPOSITE foreign key
-- into poll_options (poll_id, option_id). No trigger needed.
-- ============================================================

CREATE TABLE IF NOT EXISTS polls (
  poll_id     INTEGER      GENERATED BY DEFAULT AS IDENTITY,
  question    VARCHAR(255) NOT NULL,
  description VARCHAR(500) NULL,
  status      VARCHAR(8)   NOT NULL DEFAULT 'open',
  ends_at     TIMESTAMP    NULL,
  created_by  INTEGER      NULL,
  created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_polls PRIMARY KEY (poll_id),
  CONSTRAINT fk_polls_created_by
    FOREIGN KEY (created_by) REFERENCES users (user_id)
    ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT chk_polls_status
    CHECK (status IN ('open', 'closed'))
);

COMMENT ON COLUMN polls.ends_at    IS 'Optional auto-close deadline';
COMMENT ON COLUMN polls.created_by IS 'FK -> users.user_id, must be an admin (see trigger)';

CREATE INDEX IF NOT EXISTS idx_polls_status     ON polls (status);
CREATE INDEX IF NOT EXISTS idx_polls_created_by ON polls (created_by);

CREATE TABLE IF NOT EXISTS poll_options (
  option_id     INTEGER      GENERATED BY DEFAULT AS IDENTITY,
  poll_id       INTEGER      NOT NULL,
  option_text   VARCHAR(200) NOT NULL,
  display_order SMALLINT     NOT NULL DEFAULT 0,
  created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_poll_options PRIMARY KEY (option_id),
  -- Not redundant: the composite FK on votes needs this exact key to
  -- reference, which is what stops a vote pointing at another poll's option.
  CONSTRAINT uq_options_poll_option UNIQUE (poll_id, option_id),
  CONSTRAINT uq_options_poll_text   UNIQUE (poll_id, option_text),
  CONSTRAINT fk_options_poll
    FOREIGN KEY (poll_id) REFERENCES polls (poll_id)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT chk_options_display_order
    CHECK (display_order >= 0)
);

CREATE TABLE IF NOT EXISTS votes (
  vote_id    INTEGER   GENERATED BY DEFAULT AS IDENTITY,
  poll_id    INTEGER   NOT NULL,
  option_id  INTEGER   NOT NULL,
  user_id    INTEGER   NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_votes PRIMARY KEY (vote_id),
  CONSTRAINT uq_votes_one_per_poll UNIQUE (poll_id, user_id),
  CONSTRAINT fk_votes_option
    FOREIGN KEY (poll_id, option_id) REFERENCES poll_options (poll_id, option_id)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_votes_user
    FOREIGN KEY (user_id) REFERENCES users (user_id)
    ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_votes_option ON votes (option_id);
CREATE INDEX IF NOT EXISTS idx_votes_user   ON votes (user_id);

DROP TRIGGER IF EXISTS trg_polls_updated_at ON polls;
CREATE TRIGGER trg_polls_updated_at
BEFORE UPDATE ON polls
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_options_updated_at ON poll_options;
CREATE TRIGGER trg_options_updated_at
BEFORE UPDATE ON poll_options
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_votes_updated_at ON votes;
CREATE TRIGGER trg_votes_updated_at
BEFORE UPDATE ON votes
FOR EACH ROW EXECUTE FUNCTION set_updated_at();


-- ############################################################
-- # 007_create_notifications.sql
-- ############################################################

-- ============================================================
-- Migration 007 : notifications
-- Fan-out rows, one per recipient. A user may only ever read
-- rows where notifications.user_id = the authenticated user_id.
-- reference_type / reference_id let the frontend deep-link
-- (e.g. buddy_request 12  ->  /requests/12).
-- ============================================================

CREATE TABLE IF NOT EXISTS notifications (
  notification_id INTEGER      GENERATED BY DEFAULT AS IDENTITY,
  user_id         INTEGER      NOT NULL,
  type            VARCHAR(32)  NOT NULL,
  title           VARCHAR(150) NOT NULL,
  message         VARCHAR(500) NULL,
  reference_type  VARCHAR(16)  NULL,
  reference_id    INTEGER      NULL,
  -- MySQL used TINYINT(1) holding 0/1 and the repository binds 0/1 literals.
  -- SMALLINT keeps that contract; a BOOLEAN would break `is_read = 0`.
  is_read         SMALLINT     NOT NULL DEFAULT 0,
  created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_notifications PRIMARY KEY (notification_id),
  CONSTRAINT fk_notifications_user
    FOREIGN KEY (user_id) REFERENCES users (user_id)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT chk_notifications_type
    CHECK (type IN (
      'buddy_request',
      'buddy_request_accepted',
      'buddy_request_rejected',
      'new_competition',
      'new_lost_found',
      'new_poll'
    )),
  CONSTRAINT chk_notifications_reference_type
    CHECK (reference_type IS NULL OR reference_type IN (
      'buddy_request', 'competition', 'lost_found', 'poll'
    )),
  CONSTRAINT chk_notifications_is_read
    CHECK (is_read IN (0, 1))
);

COMMENT ON COLUMN notifications.user_id IS 'Recipient';

CREATE INDEX IF NOT EXISTS idx_notifications_user_read
  ON notifications (user_id, is_read, created_at);

DROP TRIGGER IF EXISTS trg_notifications_updated_at ON notifications;
CREATE TRIGGER trg_notifications_updated_at
BEFORE UPDATE ON notifications
FOR EACH ROW EXECUTE FUNCTION set_updated_at();


-- ############################################################
-- # 008_create_views_and_triggers.sql
-- ############################################################

-- ============================================================
-- Migration 008 : views + integrity triggers
--
-- VIEWS
--   v_buddy_matches  : an accepted request expanded into BOTH
--                      directions, so "my matches" is one indexed
--                      lookup instead of an OR across two columns.
--   v_poll_results   : per-option vote counts + percentage.
--
-- TRIGGERS (defence in depth - the API already checks the role)
--   competitions / polls : created_by must be an admin user
--   votes                : cannot vote on a closed / expired poll
--
-- MySQL -> PostgreSQL notes for this file:
--   SIGNAL SQLSTATE '45000'  -> RAISE EXCEPTION (SQLSTATE P0001)
--   NEW.x <=> OLD.x          -> NEW.x IS NOT DISTINCT FROM OLD.x
--   trigger body inline      -> a named FUNCTION the trigger calls
--   ROUND(bigint / .., 2)    -> the numerator is cast to numeric first,
--                               because PostgreSQL has no two-argument
--                               ROUND for double precision.
-- ============================================================

CREATE OR REPLACE VIEW v_buddy_matches AS
SELECT r.request_id, r.sender_id   AS user_id, r.receiver_id AS matched_user_id, r.updated_at AS matched_at
FROM   buddy_requests r
WHERE  r.status = 'accepted'
UNION ALL
SELECT r.request_id, r.receiver_id AS user_id, r.sender_id   AS matched_user_id, r.updated_at AS matched_at
FROM   buddy_requests r
WHERE  r.status = 'accepted';

CREATE OR REPLACE VIEW v_poll_results AS
SELECT
  o.poll_id,
  o.option_id,
  o.option_text,
  o.display_order,
  COUNT(v.vote_id) AS vote_count,
  ROUND(
    100 * COUNT(v.vote_id)::numeric /
    NULLIF((SELECT COUNT(*) FROM votes tv WHERE tv.poll_id = o.poll_id), 0),
    2
  ) AS vote_percentage
FROM poll_options o
LEFT JOIN votes v ON v.option_id = o.option_id
GROUP BY o.poll_id, o.option_id, o.option_text, o.display_order;

-- ------------------------------------------------------------
-- created_by must be an admin (competitions and polls)
-- ------------------------------------------------------------
CREATE OR REPLACE FUNCTION trg_assert_created_by_admin()
RETURNS TRIGGER AS $$
DECLARE
  v_role VARCHAR(16);
BEGIN
  -- On UPDATE, only re-check when created_by actually changed, so an
  -- ordinary edit does not fail because the original admin was demoted.
  IF TG_OP = 'UPDATE' AND NEW.created_by IS NOT DISTINCT FROM OLD.created_by THEN
    RETURN NEW;
  END IF;

  IF NEW.created_by IS NOT NULL THEN
    SELECT role INTO v_role FROM users WHERE user_id = NEW.created_by;
    IF v_role IS NULL OR v_role <> 'admin' THEN
      RAISE EXCEPTION '%.created_by must reference a user with role = admin', TG_TABLE_NAME;
    END IF;
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_competitions_admin_bi ON competitions;
CREATE TRIGGER trg_competitions_admin_bi
BEFORE INSERT ON competitions
FOR EACH ROW EXECUTE FUNCTION trg_assert_created_by_admin();

DROP TRIGGER IF EXISTS trg_competitions_admin_bu ON competitions;
CREATE TRIGGER trg_competitions_admin_bu
BEFORE UPDATE ON competitions
FOR EACH ROW EXECUTE FUNCTION trg_assert_created_by_admin();

DROP TRIGGER IF EXISTS trg_polls_admin_bi ON polls;
CREATE TRIGGER trg_polls_admin_bi
BEFORE INSERT ON polls
FOR EACH ROW EXECUTE FUNCTION trg_assert_created_by_admin();

DROP TRIGGER IF EXISTS trg_polls_admin_bu ON polls;
CREATE TRIGGER trg_polls_admin_bu
BEFORE UPDATE ON polls
FOR EACH ROW EXECUTE FUNCTION trg_assert_created_by_admin();

-- ------------------------------------------------------------
-- no voting on a closed or expired poll
-- ------------------------------------------------------------
CREATE OR REPLACE FUNCTION trg_assert_poll_open()
RETURNS TRIGGER AS $$
DECLARE
  v_status  VARCHAR(16);
  v_ends_at TIMESTAMP;
BEGIN
  SELECT status, ends_at INTO v_status, v_ends_at FROM polls WHERE poll_id = NEW.poll_id;
  IF v_status IS DISTINCT FROM 'open'
     OR (v_ends_at IS NOT NULL AND v_ends_at <= CURRENT_TIMESTAMP) THEN
    RAISE EXCEPTION 'Cannot vote: this poll is closed';
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_votes_poll_open_bi ON votes;
CREATE TRIGGER trg_votes_poll_open_bi
BEFORE INSERT ON votes
FOR EACH ROW EXECUTE FUNCTION trg_assert_poll_open();


-- ############################################################
-- # 009_relax_email_domain.sql
-- ############################################################

-- ============================================================
-- Migration 009 : allow any valid email domain
-- ------------------------------------------------------------
-- The product accepts @gmail.com, @yahoo.com, @outlook.com and any
-- other valid address. Registration was previously restricted to
-- Gmail in TWO places, both of which had to change together:
--     1. backend/validators/auth.validator.js  (GMAIL_REGEX -> EMAIL_REGEX)
--     2. this CHECK constraint on users.email
-- Removing only the validator would still fail at the database with
-- a check_violation (SQLSTATE 23514).
--
-- The address is still format-validated, and the service lowercases
-- it before insert, so the pattern is lowercase-only by design.
-- Existing Gmail addresses remain valid under the broader rule.
-- ============================================================

ALTER TABLE users DROP CONSTRAINT IF EXISTS chk_users_email_gmail;

ALTER TABLE users DROP CONSTRAINT IF EXISTS chk_users_email_format;
ALTER TABLE users ADD CONSTRAINT chk_users_email_format
  CHECK (email ~ '^[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,}$');
