-- ============================================================
-- Migration 001 : users
-- Core account table. Roles are NEVER chosen by the client:
-- the API always inserts 'student'; admins are promoted manually.
-- Only @gmail.com addresses are accepted (relaxed in migration 009).
--
-- PORTED FROM MySQL: this project originally ran on MySQL. The
-- differences that matter across every migration file:
--   AUTO_INCREMENT      -> GENERATED BY DEFAULT AS IDENTITY
--                          ("BY DEFAULT", not "ALWAYS", so seed.sql can
--                           still insert explicit ids)
--   ENUM('a','b')       -> VARCHAR + CHECK constraint. A native PostgreSQL
--                          enum would also work, but a CHECK keeps every
--                          column plain text, so the driver never has to
--                          cast a bound parameter into a custom type.
--   KEY idx_... (...)   -> a separate CREATE INDEX statement
--   COMMENT '...'       -> COMMENT ON COLUMN
--   ON UPDATE CURRENT_TIMESTAMP -> set_updated_at(), the trigger below
--   REGEXP              -> the ~ operator
-- ============================================================

-- ------------------------------------------------------------
-- Shared trigger function: MySQL keeps updated_at current by itself with
-- "ON UPDATE CURRENT_TIMESTAMP". PostgreSQL has no such column clause, so
-- every table below attaches this BEFORE UPDATE trigger instead.
-- ------------------------------------------------------------
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at := CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TABLE IF NOT EXISTS users (
  user_id       INTEGER      GENERATED BY DEFAULT AS IDENTITY,
  name          VARCHAR(100) NOT NULL,
  email         VARCHAR(191) NOT NULL,
  tnt           VARCHAR(30)  NOT NULL,
  academic_year VARCHAR(30)  NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  role          VARCHAR(16)  NOT NULL DEFAULT 'student',
  created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_users PRIMARY KEY (user_id),
  CONSTRAINT uq_users_email UNIQUE (email),
  CONSTRAINT uq_users_tnt   UNIQUE (tnt),
  CONSTRAINT chk_users_role
    CHECK (role IN ('student', 'admin')),
  CONSTRAINT chk_users_email_gmail
    CHECK (email ~ '^[a-z0-9._%+-]+@gmail\.com$'),
  CONSTRAINT chk_users_name_not_blank
    CHECK (char_length(trim(name)) >= 2)
);

COMMENT ON COLUMN users.tnt           IS 'University roll / TNT number, unique per student';
COMMENT ON COLUMN users.academic_year IS 'e.g. "1st Year", "2nd Year", "Final Year"';
COMMENT ON COLUMN users.password_hash IS 'bcrypt hash - plaintext is never stored';

CREATE INDEX IF NOT EXISTS idx_users_role ON users (role);

DROP TRIGGER IF EXISTS trg_users_updated_at ON users;
CREATE TRIGGER trg_users_updated_at
BEFORE UPDATE ON users
FOR EACH ROW EXECUTE FUNCTION set_updated_at();
