-- ============================================================
-- Migration 002 : study_buddy_profiles
-- Exactly ONE profile per user (enforced by uq_profiles_user_id).
-- telegram / viber are PRIVATE columns: the repository layer has
-- a "public" projection that never selects them, and they are only
-- read through the match-aware query path.
-- ============================================================

CREATE TABLE IF NOT EXISTS study_buddy_profiles (
  profile_id      INTEGER       GENERATED BY DEFAULT AS IDENTITY,
  user_id         INTEGER       NOT NULL,
  nickname        VARCHAR(60)   NOT NULL,
  semester        VARCHAR(30)   NOT NULL,
  study_style     VARCHAR(20)   NOT NULL DEFAULT 'mixed',
  weak_subjects   VARCHAR(500)  NULL,
  strong_subjects VARCHAR(500)  NULL,
  wanna_meet      VARCHAR(12)   NOT NULL DEFAULT 'both',
  notes           VARCHAR(1000) NULL,
  telegram        VARCHAR(100)  NULL,
  viber           VARCHAR(100)  NULL,
  created_at      TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at      TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_profiles PRIMARY KEY (profile_id),
  CONSTRAINT uq_profiles_user_id UNIQUE (user_id),
  CONSTRAINT fk_profiles_user
    FOREIGN KEY (user_id) REFERENCES users (user_id)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT chk_profiles_study_style
    CHECK (study_style IN ('solo_focus', 'group_discussion', 'quiet_library', 'online_call', 'mixed')),
  CONSTRAINT chk_profiles_wanna_meet
    CHECK (wanna_meet IN ('online', 'in_person', 'both')),
  CONSTRAINT chk_profiles_has_contact
    CHECK (telegram IS NOT NULL OR viber IS NOT NULL)
);

COMMENT ON COLUMN study_buddy_profiles.semester        IS 'e.g. "Semester 1" ... "Semester 8"';
COMMENT ON COLUMN study_buddy_profiles.weak_subjects   IS 'Comma separated subject list';
COMMENT ON COLUMN study_buddy_profiles.strong_subjects IS 'Comma separated subject list';
COMMENT ON COLUMN study_buddy_profiles.telegram        IS 'PRIVATE - @username or t.me link, revealed only on mutual match';
COMMENT ON COLUMN study_buddy_profiles.viber           IS 'PRIVATE - phone or viber link, revealed only on mutual match';

CREATE INDEX IF NOT EXISTS idx_profiles_semester    ON study_buddy_profiles (semester);
CREATE INDEX IF NOT EXISTS idx_profiles_study_style ON study_buddy_profiles (study_style);
CREATE INDEX IF NOT EXISTS idx_profiles_wanna_meet  ON study_buddy_profiles (wanna_meet);

DROP TRIGGER IF EXISTS trg_profiles_updated_at ON study_buddy_profiles;
CREATE TRIGGER trg_profiles_updated_at
BEFORE UPDATE ON study_buddy_profiles
FOR EACH ROW EXECUTE FUNCTION set_updated_at();
