-- ============================================================
-- Migration 003 : buddy_requests
-- One row per (sender -> receiver) direction.
--   * trg_requests_not_self_* : a user can never request themselves
--   * uq_requests_pair        : no duplicate request in the same direction
--                               (a rejected row is revived to 'pending'
--                                by the service instead of inserting a dup)
-- A MUTUAL MATCH is simply status = 'accepted'.
--
-- WHY A TRIGGER AND NOT A CHECK CONSTRAINT
-- PostgreSQL would happily accept CHECK (sender_id <> receiver_id) here -
-- the restriction that forced a trigger was MySQL's, which prohibits foreign
-- key referential actions on any column named in a CHECK. The trigger is kept
-- so the rejection message stays identical to the one the API already
-- surfaces, and so this file still mirrors the schema it was ported from.
-- ============================================================

CREATE TABLE IF NOT EXISTS buddy_requests (
  request_id  INTEGER     GENERATED BY DEFAULT AS IDENTITY,
  sender_id   INTEGER     NOT NULL,
  receiver_id INTEGER     NOT NULL,
  status      VARCHAR(12) NOT NULL DEFAULT 'pending',
  created_at  TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at  TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_requests PRIMARY KEY (request_id),
  CONSTRAINT uq_requests_pair UNIQUE (sender_id, receiver_id),
  CONSTRAINT fk_requests_sender
    FOREIGN KEY (sender_id) REFERENCES users (user_id)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_requests_receiver
    FOREIGN KEY (receiver_id) REFERENCES users (user_id)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT chk_requests_status
    CHECK (status IN ('pending', 'accepted', 'rejected'))
);

CREATE INDEX IF NOT EXISTS idx_requests_receiver_status ON buddy_requests (receiver_id, status);
CREATE INDEX IF NOT EXISTS idx_requests_sender_status   ON buddy_requests (sender_id, status);

-- MySQL raised this with SIGNAL SQLSTATE '45000'; the PostgreSQL equivalent
-- is RAISE EXCEPTION, which reports SQLSTATE P0001. error.middleware.js maps
-- P0001 to a 422 and shows the message text, exactly as it did for 45000.
CREATE OR REPLACE FUNCTION trg_requests_not_self()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.sender_id = NEW.receiver_id THEN
    RAISE EXCEPTION 'You cannot send a buddy request to yourself';
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_requests_not_self_bi ON buddy_requests;
CREATE TRIGGER trg_requests_not_self_bi
BEFORE INSERT ON buddy_requests
FOR EACH ROW EXECUTE FUNCTION trg_requests_not_self();

DROP TRIGGER IF EXISTS trg_requests_not_self_bu ON buddy_requests;
CREATE TRIGGER trg_requests_not_self_bu
BEFORE UPDATE ON buddy_requests
FOR EACH ROW EXECUTE FUNCTION trg_requests_not_self();

DROP TRIGGER IF EXISTS trg_requests_updated_at ON buddy_requests;
CREATE TRIGGER trg_requests_updated_at
BEFORE UPDATE ON buddy_requests
FOR EACH ROW EXECUTE FUNCTION set_updated_at();
