-- ============================================================
-- Migration 004 : competitions
-- ADMIN-ONLY write table. Enforcement is layered:
--   1. route  -> authenticate + requireAdmin middleware
--   2. DB     -> trigger in migration 008 rejects a created_by
--                that is not an admin user (defence in depth)
-- Students can only read.
-- ============================================================

CREATE TABLE IF NOT EXISTS competitions (
  competition_id INTEGER      GENERATED BY DEFAULT AS IDENTITY,
  title          VARCHAR(150) NOT NULL,
  description    TEXT         NULL,
  event_date     DATE         NOT NULL,
  event_time     TIME         NULL,
  location       VARCHAR(150) NULL,
  organizer      VARCHAR(120) NULL,
  image_url      VARCHAR(500) NULL,
  created_by     INTEGER      NULL,
  created_at     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_competitions PRIMARY KEY (competition_id),
  CONSTRAINT fk_competitions_created_by
    FOREIGN KEY (created_by) REFERENCES users (user_id)
    ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT chk_competitions_title_not_blank
    CHECK (char_length(trim(title)) >= 3)
);

COMMENT ON COLUMN competitions.created_by IS 'FK -> users.user_id, must be an admin (see trigger)';

CREATE INDEX IF NOT EXISTS idx_competitions_event_date ON competitions (event_date);
CREATE INDEX IF NOT EXISTS idx_competitions_created_by ON competitions (created_by);

DROP TRIGGER IF EXISTS trg_competitions_updated_at ON competitions;
CREATE TRIGGER trg_competitions_updated_at
BEFORE UPDATE ON competitions
FOR EACH ROW EXECUTE FUNCTION set_updated_at();
