-- ============================================================
-- Migration 005 : lost_found
-- Any student may post. Ownership rule (owner OR admin) is
-- enforced in lostFound.service.js on update/delete.
-- ============================================================

CREATE TABLE IF NOT EXISTS lost_found (
  item_id      INTEGER      GENERATED BY DEFAULT AS IDENTITY,
  user_id      INTEGER      NOT NULL,
  type         VARCHAR(8)   NOT NULL,
  title        VARCHAR(150) NOT NULL,
  description  TEXT         NULL,
  location     VARCHAR(150) NULL,
  item_date    DATE         NULL,
  image_url    VARCHAR(500) NULL,
  contact_info VARCHAR(150) NULL,
  status       VARCHAR(10)  NOT NULL DEFAULT 'active',
  created_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_lost_found PRIMARY KEY (item_id),
  CONSTRAINT fk_lost_found_user
    FOREIGN KEY (user_id) REFERENCES users (user_id)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT chk_lost_found_type
    CHECK (type IN ('lost', 'found')),
  CONSTRAINT chk_lost_found_status
    CHECK (status IN ('active', 'resolved')),
  CONSTRAINT chk_lost_found_title_not_blank
    CHECK (char_length(trim(title)) >= 3)
);

COMMENT ON COLUMN lost_found.item_date    IS 'Date the item was lost / found';
COMMENT ON COLUMN lost_found.contact_info IS 'Public on purpose - poster chooses what to show';

CREATE INDEX IF NOT EXISTS idx_lost_found_user        ON lost_found (user_id);
CREATE INDEX IF NOT EXISTS idx_lost_found_type_status ON lost_found (type, status);
CREATE INDEX IF NOT EXISTS idx_lost_found_created_at  ON lost_found (created_at);

DROP TRIGGER IF EXISTS trg_lost_found_updated_at ON lost_found;
CREATE TRIGGER trg_lost_found_updated_at
BEFORE UPDATE ON lost_found
FOR EACH ROW EXECUTE FUNCTION set_updated_at();
