-- ============================================================
-- Migration 006 : polls, poll_options, votes
--
-- "One vote per user per poll" is enforced BY THE DATABASE with
--   UNIQUE (poll_id, user_id)  -> uq_votes_one_per_poll
--
-- A vote can also never point at an option from a different poll:
-- votes carries (poll_id, option_id) and a COMPOSITE foreign key
-- into poll_options (poll_id, option_id). No trigger needed.
-- ============================================================

CREATE TABLE IF NOT EXISTS polls (
  poll_id     INTEGER      GENERATED BY DEFAULT AS IDENTITY,
  question    VARCHAR(255) NOT NULL,
  description VARCHAR(500) NULL,
  status      VARCHAR(8)   NOT NULL DEFAULT 'open',
  ends_at     TIMESTAMP    NULL,
  created_by  INTEGER      NULL,
  created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_polls PRIMARY KEY (poll_id),
  CONSTRAINT fk_polls_created_by
    FOREIGN KEY (created_by) REFERENCES users (user_id)
    ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT chk_polls_status
    CHECK (status IN ('open', 'closed'))
);

COMMENT ON COLUMN polls.ends_at    IS 'Optional auto-close deadline';
COMMENT ON COLUMN polls.created_by IS 'FK -> users.user_id, must be an admin (see trigger)';

CREATE INDEX IF NOT EXISTS idx_polls_status     ON polls (status);
CREATE INDEX IF NOT EXISTS idx_polls_created_by ON polls (created_by);

CREATE TABLE IF NOT EXISTS poll_options (
  option_id     INTEGER      GENERATED BY DEFAULT AS IDENTITY,
  poll_id       INTEGER      NOT NULL,
  option_text   VARCHAR(200) NOT NULL,
  display_order SMALLINT     NOT NULL DEFAULT 0,
  created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_poll_options PRIMARY KEY (option_id),
  -- Not redundant: the composite FK on votes needs this exact key to
  -- reference, which is what stops a vote pointing at another poll's option.
  CONSTRAINT uq_options_poll_option UNIQUE (poll_id, option_id),
  CONSTRAINT uq_options_poll_text   UNIQUE (poll_id, option_text),
  CONSTRAINT fk_options_poll
    FOREIGN KEY (poll_id) REFERENCES polls (poll_id)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT chk_options_display_order
    CHECK (display_order >= 0)
);

CREATE TABLE IF NOT EXISTS votes (
  vote_id    INTEGER   GENERATED BY DEFAULT AS IDENTITY,
  poll_id    INTEGER   NOT NULL,
  option_id  INTEGER   NOT NULL,
  user_id    INTEGER   NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_votes PRIMARY KEY (vote_id),
  CONSTRAINT uq_votes_one_per_poll UNIQUE (poll_id, user_id),
  CONSTRAINT fk_votes_option
    FOREIGN KEY (poll_id, option_id) REFERENCES poll_options (poll_id, option_id)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_votes_user
    FOREIGN KEY (user_id) REFERENCES users (user_id)
    ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_votes_option ON votes (option_id);
CREATE INDEX IF NOT EXISTS idx_votes_user   ON votes (user_id);

DROP TRIGGER IF EXISTS trg_polls_updated_at ON polls;
CREATE TRIGGER trg_polls_updated_at
BEFORE UPDATE ON polls
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_options_updated_at ON poll_options;
CREATE TRIGGER trg_options_updated_at
BEFORE UPDATE ON poll_options
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_votes_updated_at ON votes;
CREATE TRIGGER trg_votes_updated_at
BEFORE UPDATE ON votes
FOR EACH ROW EXECUTE FUNCTION set_updated_at();
