-- ============================================================
-- Migration 007 : notifications
-- Fan-out rows, one per recipient. A user may only ever read
-- rows where notifications.user_id = the authenticated user_id.
-- reference_type / reference_id let the frontend deep-link
-- (e.g. buddy_request 12  ->  /requests/12).
-- ============================================================

CREATE TABLE IF NOT EXISTS notifications (
  notification_id INTEGER      GENERATED BY DEFAULT AS IDENTITY,
  user_id         INTEGER      NOT NULL,
  type            VARCHAR(32)  NOT NULL,
  title           VARCHAR(150) NOT NULL,
  message         VARCHAR(500) NULL,
  reference_type  VARCHAR(16)  NULL,
  reference_id    INTEGER      NULL,
  -- MySQL used TINYINT(1) holding 0/1 and the repository binds 0/1 literals.
  -- SMALLINT keeps that contract; a BOOLEAN would break `is_read = 0`.
  is_read         SMALLINT     NOT NULL DEFAULT 0,
  created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_notifications PRIMARY KEY (notification_id),
  CONSTRAINT fk_notifications_user
    FOREIGN KEY (user_id) REFERENCES users (user_id)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT chk_notifications_type
    CHECK (type IN (
      'buddy_request',
      'buddy_request_accepted',
      'buddy_request_rejected',
      'new_competition',
      'new_lost_found',
      'new_poll'
    )),
  CONSTRAINT chk_notifications_reference_type
    CHECK (reference_type IS NULL OR reference_type IN (
      'buddy_request', 'competition', 'lost_found', 'poll'
    )),
  CONSTRAINT chk_notifications_is_read
    CHECK (is_read IN (0, 1))
);

COMMENT ON COLUMN notifications.user_id IS 'Recipient';

CREATE INDEX IF NOT EXISTS idx_notifications_user_read
  ON notifications (user_id, is_read, created_at);

DROP TRIGGER IF EXISTS trg_notifications_updated_at ON notifications;
CREATE TRIGGER trg_notifications_updated_at
BEFORE UPDATE ON notifications
FOR EACH ROW EXECUTE FUNCTION set_updated_at();
