'use strict';

/**
 * Applies every pending file in database/migrations, in filename order, and
 * records it in the `schema_migrations` table so re-running is safe.
 *
 * PostgreSQL DDL is transactional, so each migration file plus its ledger row
 * commit together: a file that fails halfway leaves the schema exactly as it
 * was, and the run stops there reporting which file broke.
 */

const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const { Client } = require('pg');

const { env } = require('../../config/env');
const { baseConnectionConfig } = require('../../config/database');
const logger = require('../../utils/logger');
const { runSqlFile, readSqlFile } = require('./sql-runner');
const { explainConnectionError } = require('./create-database');

// The SQL now lives in the repository-root database/ folder (see database/README.md),
// not inside backend/. From backend/scripts/db/ that is three levels up.
const MIGRATIONS_DIR = path.resolve(__dirname, '..', '..', '..', 'database', 'migrations');

const TRACKING_TABLE = `
  CREATE TABLE IF NOT EXISTS schema_migrations (
    id          INTEGER      GENERATED BY DEFAULT AS IDENTITY,
    filename    VARCHAR(255) NOT NULL,
    checksum    CHAR(64)     NOT NULL,
    applied_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_schema_migrations PRIMARY KEY (id),
    CONSTRAINT uq_migrations_filename UNIQUE (filename)
  )`;

/** @returns {string[]} sorted migration filenames */
function listMigrationFiles() {
  if (!fs.existsSync(MIGRATIONS_DIR)) return [];
  return fs
    .readdirSync(MIGRATIONS_DIR)
    .filter((file) => file.endsWith('.sql'))
    .sort();
}

const checksumOf = (filePath) =>
  crypto.createHash('sha256').update(readSqlFile(filePath)).digest('hex');

/** Connect directly to the application database. */
async function connect() {
  const client = new Client(baseConnectionConfig({ withDatabase: true }));
  try {
    await client.connect();
    return client;
  } catch (error) {
    // 3D000 = invalid_catalog_name
    if (error.code === '3D000') {
      error.friendlyMessage =
        `Database "${env.db.database}" does not exist yet.
  Run: npm run db:setup`;
    } else {
      error.friendlyMessage = explainConnectionError(error);
    }
    throw error;
  }
}

/** @returns {Promise<{ applied: string[], skipped: string[] }>} */
async function migrate() {
  const connection = await connect();

  try {
    await connection.query(TRACKING_TABLE);

    const { rows } = await connection.query('SELECT filename, checksum FROM schema_migrations');
    const appliedMap = new Map(rows.map((row) => [row.filename, row.checksum]));

    const files = listMigrationFiles();
    if (files.length === 0) {
      logger.warn('No migration files found in database/migrations');
      return { applied: [], skipped: [] };
    }

    const applied = [];
    const skipped = [];

    for (const file of files) {
      const filePath = path.join(MIGRATIONS_DIR, file);
      const checksum = checksumOf(filePath);

      if (appliedMap.has(file)) {
        if (appliedMap.get(file) !== checksum) {
          logger.warn(
            `${file} has changed since it was applied. ` +
              'Existing databases keep the old schema - use `npm run db:reset` to rebuild.'
          );
        }
        skipped.push(file);
        continue;
      }

      // The file and its ledger row go in together, so a crash between the
      // two cannot leave a migration applied but unrecorded.
      // eslint-disable-next-line no-await-in-loop
      await connection.query('BEGIN');
      let count;
      try {
        // eslint-disable-next-line no-await-in-loop
        count = await runSqlFile(connection, filePath);
        // eslint-disable-next-line no-await-in-loop
        await connection.query(
          'INSERT INTO schema_migrations (filename, checksum) VALUES ($1, $2)',
          [file, checksum]
        );
        // eslint-disable-next-line no-await-in-loop
        await connection.query('COMMIT');
      } catch (error) {
        // eslint-disable-next-line no-await-in-loop
        await connection.query('ROLLBACK');
        throw error;
      }

      logger.info(`applied  ${file}  (${count} statements)`);
      applied.push(file);
    }

    if (applied.length === 0) {
      logger.info(`Schema is already up to date (${skipped.length} migrations applied earlier)`);
    } else {
      logger.info(`${applied.length} migration(s) applied, ${skipped.length} already up to date`);
    }

    return { applied, skipped };
  } finally {
    await connection.end();
  }
}

module.exports = { migrate, listMigrationFiles, MIGRATIONS_DIR, connect };

if (require.main === module) {
  migrate()
    .then(() => process.exit(0))
    .catch((error) => {
      logger.error(error.friendlyMessage || error.message);
      process.exit(1);
    });
}
